### ISSUE TITLE
Morden Vimeo Uploader is not working with AJAX

### ISSUE THREAD

**Issue by blackb2b** [gdarko/wp-vimeo-videos#21]
When you opt AJAX for the form, the Morden upload will not be able to clickable.

**Comment by gdarko** [comment]
Hello,

Is the issue resolved with the latest release? Message me with your website details  at info@codeverve.com and i will check.

Best Regards,
Darko

**Comment by blackb2b** [comment]
Hi,

Thanks, I got it worked on single page form. But the issue persists when I use page break, and place the Uploader in second page.

https://docs.gravityforms.com/page-break/

Best regards,

**Comment by blackb2b** [comment]
I commented to your plugin's github. Let me know if you need further
information.

Best regards,
